version: "3.0"

networks:
  evohtmx:
    driver: bridge

services:
  evo:
    container_name: evolution
    build:
      context: ./
      dockerfile: ./Docker/evo/Dockerfile
    volumes:
      - ./:/var/www/html/
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "5000:80"
    stdin_open: true
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 1s
    networks:
      - evohtmx

  db:
    container_name: database
    image: mysql:8.0
    env_file:
      - /Docker/.env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password && mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./Docker/dump:/docker-entrypoint-initdb.d
      - ./Docker/conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - evohtmx

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - /Docker/.env
    links:
      - db:db
    ports:
      - "5700:80"
    networks:
      - evohtmx

volumes:
  persistent:
